#lang racket
(define (leap_year_func)
  (display "Введите год ")
  (define year (read))
  (if (equal? (modulo year 4) 0) (display "Год является высокосным") (display "Год не является высокосным"))
  )

(define (help_discount price)
  (set! price (* price 0.9))
  (display "Вам предоставляется скидка 10%")
  price)
(define (check_discount)
  (display "Вычисление стоимости покупки с учетом скидки")
  (newline)
  (display "Введите сумму покупки и нажмите <Enter> ")
  (define total_price (read))
  (if (>= total_price 1000) (set! total_price(help_discount total_price)) (display ""))
  (display "Сумма покупки с учетом скидки:")
  (display total_price)
  )
(define (check_wwII)
  (display "В каком году началась вторая мировая война?")
  (display "Введите число и нажмите <Enter>")
  (define answer (read))
  (if (equal? answer 1939) (display "Верно! Вторая Мировая война началсь в 1939 году.") (display "Неверно! Вторая Мировая война началась в 1939 году."))
  )

(display "Введите 1 для определения высокосности года, 2 для подсчёта цены товара с учётом скидки, 3 для проверки знания начала Второй Мировой войны.")
(newline)
(define answer (read))
(if (equal? answer 1) (leap_year_func)
(if (equal? answer 2) (check_discount)
(if (equal? answer 3) (check_wwII) (display "Введено неверное значение"))))